# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_hired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
